config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'tasks', to: 'tasks#index'

  get 'tasks/new', to: 'tasks#new'
  post 'tasks', to: 'tasks#create'

  get 'tasks/:id', to: 'tasks#show', as: 'task'

  get 'tasks/:id/edit', to: 'tasks#edit', as: 'task_edit'
  patch 'tasks/:id', to: 'tasks#update'

  delete 'tasks/:id', to: 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
  end

  def edit
  end

  def update
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    # *Strong params*: You need to *whitelist* what can be updated by the user
    # Never trust user data!
    params.require(:task).permit(:title, :details, :completed)
  end

  def set_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |t| %>
  <div class="form-group">
  <%= t.label :title %>
  <%= t.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
  <%= t.label :details %>
  <%= t.text_field :details, class: 'form-control' %>
  </div>
  <% if @task.new_record? == false %>
    <div class="form-group">
      <%= t.check_box :completed %>
      <%= t.label :completed %>
    </div>
  <% end %>
  <%= t.submit class: 'btn btn-primary' %>
<% end %>

app/views/tasks/edit.html.erb
<h1>Edit task</h1>
<%= render 'form', task: @task %>
<%= link_to "Back to list", tasks_path  %>

app/views/tasks/index.html.erb
<h1>My tasks</h1>
<% @tasks.each do |task| %>
  <p><%= check_box_tag task, task.completed,  task.completed,completed: true %><%= link_to task[:title], task_path(task) %>
  <%= link_to(
        content_tag(
          :i,
          nil,
          class: 'fa fa-trash-o'
        ),
        method: :delete,
        data: {
          confirm: 'Are you sure?'
        }
      )
  %></p>
<% end %>

<%= link_to "Add a new task", tasks_new_path  %>

app/views/tasks/new.html.erb
<h1>New task</h1>
<%= render 'form', task: @task %>
<%= link_to "Back to list", tasks_path  %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>
<%= link_to "Edit this task", task_edit_path  %>

<p>
  <%= label_tag do %>
    <%= check_box_tag @task, @task.completed, @task.completed,completed: true %>
    <% if @task.completed %>
      <%= "This task is completed" %>
    <% else %>
      <%= "This task is not completed yet" %>
    <% end %>
  <% end %>
</p>
<%= link_to "Back to list", tasks_path  %>